spring:
  application:
    name: customer-producer
  threads:
    virtual:
      enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 30s
  kafka:
    producer:
      acks: all
      retries: 50
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        retry:
          backoff.ms: 250
