spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    template:
      default-topic: customers
    consumer:
      properties:
        schema:
          registry:
            url: "http://localhost:8081"