spring:
  application:
    name: "customer-consumer"
  kafka:
    listener:
      concurrency: 1
      type: batch
    consumer:
      client-id: customer-consumer
      group-id: customer-consumers
      # Configures the delegating Spring Kafka ErrorHandlingDeserializer
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        specific.avro.reader: true
        missing.topics.fatal: true
        # Delegate deserializers for the ErrorHandlingDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer